openapi: "3.0.2"
info:
  title: LMS REST API
  version: "1.0"
servers:
  - url: http://localhost:9000/api/v1
tags:
  - name: Server
  - name: Players  
  - name: Syncgroup
  - name: Library
  - name: Browser
  
components:
  parameters:
    playerid:
      name: playerid
      in: path
      required: true
      description: "The ID of a player"
      schema:
        type: string
    playable:
      name: playable
      in: path
      required: true
      description: "An url, playlist or directory content that represents playable items"
      schema:
        type: string
    playlistaction:
      name: playlistaction
      in: query
      required: true
      description: "Specifying a position/action to put into a playlist"
      schema:
        type: string
        enum:
          - add
          - next
          - delete
          - move
    appid:
      name: appid
      in: path
      required: true
      description: "The ID of an app"
      schema:
        type: string
    offset:
      name: offset
      in: query
      description: Paginated results offset
      schema:
        type: integer
    limit:
      name: limit
      in: query
      description: Paginated results limit
      schema:
        type: integer
paths:
  /browser:
    post:
      tags:
        - Browser
      description: "Post an action to the browser which returns the browse response"
      responses:
        "405":
          description: Not Implemented
  /browser/apps:
    get:
      tags:
        - Browser
      description: "Get the apps available to browse"
      responses:
        "405":
          description: Not Implemented
  /browser/apps/{appid}:
    get:
      parameters:
        - "$ref": "#/components/parameters/appid"
      tags:
        - Browser
      description: "Browse an apps feed"
      responses:
        "405":
          description: Not Implemented
  /browser/radios:
    get:
      tags:
        - Browser
      description: "Get the Radio items available to browse"
      responses:
        '405':
          description: Not Implemented
  /browser/favorites:
    get:
      tags:
        - Browser
      description: "Get the browse items in favorites"
      responses:
        '405':
          description: Not Implemented
  /library/tracks:
    get:
      tags: 
      - Library
      description: "Get a list of tracks that match the query"
      responses:
        '405':
          description: Not Implemented
  /library/albums:
      get:
        tags:
          - Library
        description: "Get a list of albums that match the query"
        responses:
          "405":
            description: Not Implemented
  /library/playlists:
      get:
        tags:
          - Library
        description: "Get a list of playlists that match the query"
        responses:
          "405":
            description: Not Implemented
  /syncgroup:
    get:
      tags:
        - Syncgroup
      description: "Gets the players in a syncgroup"
      responses:
         "405":
          description: Not Implemented 
  /server:
    get:
      tags:
        - Server
      description: "Get details of the LMS server"
      responses:
         "405":
          description: Not Implemented
  /server/status:
    post:
      tags:
        - Server
      parameters:
        - name: action
          in: query
          description: "Indicate a stop or restart of the server"
          schema:
            type: string
            enum:
              - stop
              - restart
      description: "Stop or Restart the server"
      responses:
         "405":
          description: Not Implemented

  /players:
    get:
      tags:
        - Players
      description: "Returns a list of players"
      responses:
        "200":
          description: OK
  /players/{playerid}:
    get:
      parameters:
        - "$ref": "#/components/parameters/playerid"
      tags:
        - Players
      description: "Returns details about a connected player"
      responses:
        "200":
          description: OK
        "404":         
          description: Not Found
  /players/{playerid}/status:
    get:
      parameters:
        - "$ref": "#/components/parameters/playerid"
      tags:
        - Players
      description: "Get the status of the current player"
      responses:
        "200":
          description: OK
        "404":         
          description: Not Found
    post:
      parameters:
        - "$ref": "#/components/parameters/playerid"
      tags:
        - Players
      description: "Change the status of a player"
      responses:
        "200":
          description: OK
        "404":         
          description: Not Found
  /players/{playerid}/play-status:
    get:
      parameters:
        - "$ref": "#/components/parameters/playerid"
      tags:
        - Players
      description: "Get's the current play status of the player (playing, stopped etc.)"
      responses:
         "405":
          description: Not Implemented
    post:
      parameters:
        - "$ref": "#/components/parameters/playerid"
        - name: action
          in: query
          description: "the play action"
          schema:
            type: string
            enum:
              - play
              - stop
              - pause
      tags:
        - Players
      description: "Set the current play status of the player"
      responses:
         "405":
          description: Not Implemented
  /players/{playerid}/song:
    get:
      parameters:
        - "$ref": "#/components/parameters/playerid"
      tags:
        - Players
      description: "Get information about the currenlty playing song"
      responses:
         "405":
          description: Not Implemented
  /players/{playerid}/queue:
    get:
      parameters:
        - "$ref": "#/components/parameters/playerid"
        - "$ref": "#/components/parameters/offset"
        - "$ref": "#/components/parameters/limit"
      tags:
        - Players
      description: "Get's the content of the current playlist for the player"
      responses:
         "405":
          description: Not Implemented
    put:
      parameters:
        - "$ref": "#/components/parameters/playerid"
        - name: playable
          in: query
          required: false
          description: "An url, playlist or directory content that represents playable items"
          schema:
            type: string
        - "$ref": "#/components/parameters/playlistaction"
        - name: indexfrom
          in: query
          required: false
          description: "An index to move from in the playlist queue"
          schema:
            type: integer
        - name: indexto
          in: query
          required: false
          description: "An index to move to in the playlist queue"
          schema:
            type: integer
      description: "Places the given playable into the players playlist queue in the position specified in action"
      tags:
        - Players
      responses:
         "405":
          description: Not Implemented
    delete:
      parameters:
        - "$ref": "#/components/parameters/playerid"
      description: "Delete and clear the playlist for the player"
      tags:
        - Players
      responses:
         "405":
          description: Not Implemented
  /players/{playerid}/queue/{playable}:
    post:
      parameters:
        - "$ref": "#/components/parameters/playerid"
        - "$ref": "#/components/parameters/playable"
      tags:
        - Players
      description: "Set's the current playlist to the value set in playable, which can be an url, directory or playlist"
      responses:
         "405":
          description: Not Implemented
  
